spring:
  application:
    name: auth.api
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

server:
  port: ${SERVER_PORT:8080}

keycloak:
  url: ${KEYCLOAK_URL:http://keycloak-service.keycloak.svc.cluster.local}
  realm: ${KEYCLOAK_REALM:customer}
  client-id: ${KEYCLOAK_CLIENT_ID:auth-api-backend}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}

app:
  frontend-base-url: ${FRONTEND_BASE_URL:https://customer.posselect.com}
  cookie-domain: ${COOKIE_DOMAIN:.posselect.com}
  cors-allowed-origin-pattern: ${CORS_ALLOWED_ORIGIN_PATTERN:https://*.posselect.com}
  mail-from: ${MAIL_FROM:customer-service@posselect.com}
  brand-name: ${BRAND_NAME:posselect.com}
